---
title: Fruit machine
hero_image: images/banner.png
description:
version: 4
listed: true
copyedit: true
last_tested: '2018-12-06'
steps:
- title: Introduction
  completion: engaged
- title: Import images
- title: Random choices
- title: Build a game
- title: Make the game playable
- title: Keep score
  completion: internal
- title: Create a game interface
- title: 'Challenge: end the game'
  challenge: true
